### ISSUE TITLE
Add simple ruler to indicate scale

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/segmentation-labeling-app#69]
# Overview
Add scale bar with units in um to indicate scale of images. This image scale needs to be constructed from the ophys_experiment.movie_width and display some value of length to understand scale of ROI in image. This scale bar should live in the bottom left of every image produced. This scale bar will help science team to gain clarity on the size or ROIs from one labeling task to the next.

# ToDo:
- [x] Query LIMs to get the movie_width for given ophys exp id (changed to scientifica default resolution, add querying of LIMs later if neccesary)
- [x] Create 10um sized scale object for small view and 40um sized scale for full view from the movie width value
- [x] Append scale object onto image array before saving

# Notes:
### Output Example
![image.png](https://images.zenhubusercontent.com/5dde9d05537fdc0001b7a121/c5fba7b6-9c98-4e67-bad3-2e20c7012e4e)
This image is a good start but needs to have the value of the scale size added on or clarified somehow

### LIMs query for movie width example
This LIMS query should work for Scientifica at least:

```
SELECT os.id AS os_id, oe.id AS oe_id, sc.resolution FROM ophys_experiments oe 
JOIN ophys_sessions os ON os.id=oe.ophys_session_id 
JOIN images im ON im.id=oe.ophys_primary_image_id 
JOIN scans sc ON sc.image_id=im.id 
WHERE os.id = 1012846464;
```

**Comment by isaak-willett** [comment]
Design of Ruler

# Overview:
A ruler is desired to be added to give a sense of scale to the projection images displayed in ground truth web app. This will help the science team to better understand the scale at which the images are presented to inform their decisions on the validity of a ROI.

# Design Requirements:
* The ruler must have an indication of the size in pixels
* The ruler must not cover any piece of the projection image
* The ruler must acurately label the scale of the images in relation to the original image/video
* A png must be created from a numpy array that has a ruler embedded

# Proposed Design
The ruler will be embedded in the images that are created during the transformation pipeline. The scale indication will therefore be part of the images that are created. The projection images will loosely resemble the below mock up.
![image.png](https://images.zenhubusercontent.com/5dde9d05537fdc0001b7a121/f04edb37-cf4e-40d1-a303-227c29731017)

# API Design
The api will be designed such that it takes a two dimensional numpy array, and a original size tuple. The function will transform the numpy array into a matplotlib figure and add the ruler on as an annotation to the image. The generated figure will be returned.
```python
def add_ruler(projection_image: np.array, original_size: Tuple[int, int]):
     # logic of code
    return pyplot_figure
```

# Technical Details
* The Numpy array will be padded by 10 pixels on the bottom edge to make room for the ruler
* The Numpy array will be transformed into a matplotlib figure
* The function will make use of matplotlib annotations to draw the arrows and the scale label on the figure
* The function will use 'darrow' shape to make a 10 pixel tall arrow that spans the base of the image and contains text denoting the scale

# Other Options
The scale addition can be done later in the HTML but this requires saving the metadata needed to know the scale at which the image exists. This data is more easily accessible at the time transformation is occurring. Additionally an option to turn on and off the ruler display in the HTML would be required and this is not work that should be prioritized.

**Comment by kschelonka** [comment]
@djkapner @wbwakeman (cc: @matchings) Is there a fixed "zoom" level for the microscopes? The movies are 512x512 pixels, and we are taking 128x128 crops from them. So if the "zoom" level is fixed then we can compute the number of um for the 128x128 window.

Depending on size, maybe a 10um scale ruler in the 10px space under the image is the most useful.

**Comment by kschelonka** [comment]
>The Numpy array will be padded by 10 pixels on the bottom edge to make room for the ruler
> The Numpy array will be transformed into a matplotlib figure

It would probably be easier to generate a 10px .png and tack it onto the bottom of the image that's exported as a .png, rather than using a numpy array. 

If the "zoom" level is indeed fixed, we could generate this resource ahead of time using image processing software, like: |----10 um----| (but in image form)

**Comment by djkapner** [comment]
I think 512 pixels = 400um. Jerome says always.

**Comment by wbwakeman** [comment]
Because of scientifica dewarping, the width of the frame may be less than 512.  This is recorded in ophys_experiments.movie_width 

We also record resolution, which I believe for most Scientificas is 0.78125 microns/pixel.

**Comment by kschelonka** [comment]
Oh great, the resolution is exactly what we need to generate this annotation. Where can this data be found @wbwakeman ?

**Comment by wbwakeman** [comment]
What exactly is it that you want to get the resolution of?  The timeseries movie, one of the static images, such as the maximum projection image, or something else?

**Comment by kschelonka** [comment]
We use the time series movie to redo the static projection images, so I think we just need the resolution of the movie.

**Comment by isaak-willett** [comment]
Is the resolution of the movie static or is it dynamic, it seems to me that things are moving under the microscope and our depth and therefore resolution changes slightly?

**Comment by wbwakeman** [comment]
This LIMS query should work for Scientifica at least:

```
SELECT os.id AS os_id, oe.id AS oe_id, sc.resolution FROM ophys_experiments oe 
JOIN ophys_sessions os ON os.id=oe.ophys_session_id 
JOIN images im ON im.id=oe.ophys_primary_image_id 
JOIN scans sc ON sc.image_id=im.id 
WHERE os.id = 1012846464;
```

**Comment by isaak-willett** [comment]
That's incredibly helpful, thanks wayne!

**Comment by djkapner** [comment]
I recommend not changing the sizes of any frames or images and just adding a small scale bar like so to one corner of each frame/image:
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/5a22d5d7-ca02-42c3-bb08-c1e9138afee7)
It is unllikely to obscure anything of importance and then your changes don't need to muck with shapes and sizes. Your api could just take in an image (array) and output an image (array) with that tacked on there.

**Comment by kschelonka** [comment]
>It is unllikely to obscure anything of importance and then your changes don't need to muck with shapes and sizes.

It would definitely be nicer to have a scale bar on the image so that we don't have to make any UI updates, but I am somewhat concerned about the edges. Unless we're no longer showing ROIs very close to the border?

**Comment by djkapner** [comment]
the ROIs are always centered in the sub-frames

**Comment by kschelonka** [comment]
Oh, duh. You're right. I had in my head a prior version I think. @isaak-willett I think we can annotate directly on the image without issues, so we don't need to add any additional padding.

**Comment by djkapner** [comment]
with all due respect to zenhub, this is a terrible forum for a conversation

**Comment by isaak-willett** [comment]
It's awful, I'll just slack you all

**Comment by matchings** [comment]
i'm a bit late to the party here, but why do we need a scale bar on the actual image?

**Comment by kschelonka** [comment]
It was a request from Jerome to help give some context to the images.

**Comment by matchings** [comment]
ah ok, I confused myself here, I read the thread for this issue and thought it was about [this SDK issue,](https://github.com/AllenInstitute/AllenSDK/issues/1492) about image resolution, and totally didn't notice that this is about the segmentation tool. Sorry! Don't mind me...
